/*global systemDictionary:true */
"use strict";

systemDictionary = 
{
  "Adaptersettings for Find-Me": {
    "en": "Adaptersettings for Find-Me",
    "de": "Adaptereinstellungen für Find-Me",
    "ru": "Настройки адаптера для Find-Me",
    "pt": "Ajustes de adaptador para Find-Me",
    "nl": "Adaptersinstellingen voor Find-Me",
    "fr": "Paramètres de l'adaptateur pour Find-Me",
    "it": "Adaptersettings for Find-Me",
    "es": "Ajustes de adaptadores para Find-Me",
    "pl": "Ustawienia adapterów dla Find-Me",
    "zh-cn": "Find-Me的适配器设置"
  },
  "Timezone": {
    "en": "Timezone",
    "de": "Zeitzone",
    "ru": "Часовой пояс",
    "pt": "Fuso horário",
    "nl": "Tijdzone",
    "fr": "Fuseau horaire",
    "it": "Fuso orario",
    "es": "Zona horaria",
    "pl": "Strefa czasowa",
    "zh-cn": "时区"
  },
  "Date / Time Format": {
    "en": "Date / Time Format",
    "de": "Datums- / Uhrzeitformat",
    "ru": "Формат даты / времени",
    "pt": "Formato de data / hora",
    "nl": "Datum- / tijdformaat",
    "fr": "Format date / heure",
    "it": "Formato data / ora",
    "es": "Formato de fecha / hora",
    "pl": "Format daty / godziny",
    "zh-cn": "日期/时间格式"
  },
  "Username": {
    "en": "Username",
    "de": "Nutzername",
    "ru": "Имя пользователя",
    "pt": "Nome do usuário",
    "nl": "Gebruikersnaam",
    "fr": "Nom d'utilisateur",
    "it": "Nome utente",
    "es": "Nombre de usuario",
    "pl": "Nazwa Użytkownika",
    "zh-cn": "用户名"
  },
  "Password": {
    "en": "Password",
    "de": "Passwort",
    "ru": "пароль",
    "pt": "Senha",
    "nl": "Wachtwoord",
    "fr": "Mot de passe",
    "it": "Parola d'ordine",
    "es": "Contraseña",
    "pl": "Hasło",
    "zh-cn": "密码"
  },
  "Bing-Maps (API-KEY)": {
    "en": "Bing-Maps (API-KEY)",
    "de": "Bing-Maps (API-KEY)",
    "ru": "Bing-Maps (API-KEY)",
    "pt": "Bing-Maps (API-KEY)",
    "nl": "Bing-Maps (API-KEY)",
    "fr": "Bing-Maps (API-KEY)",
    "it": "Bing-Maps (API-KEY)",
    "es": "Bing-Maps (API-KEY)",
    "pl": "Bing-Maps (klucz API)",
    "zh-cn": "必应地图（API-KEY）"
  },
  "Refresh Intervall": {
    "en": "Refresh Intervall",
    "de": "Aktualisierungs-Intervall",
    "ru": "Обновить интервал",
    "pt": "Atualizar intervalo",
    "nl": "Vernieuw Intervall",
    "fr": "Actualiser l'intervalle",
    "it": "Aggiorna intervallo",
    "es": "Actualizar intervalo",
    "pl": "Odśwież interwał",
    "zh-cn": "刷新间隔"
  },
  "Disabled": {
    "en": "Disabled",
    "de": "Deaktiviert",
    "ru": "инвалид",
    "pt": "Deficientes",
    "nl": "Gehandicapt",
    "fr": "Désactivé",
    "it": "Disabilitata",
    "es": "Desactivado",
    "pl": "Niepełnosprawny",
    "zh-cn": "禁用"
  },
  "Every minute": {
    "en": "Every minute",
    "de": "Jede Minute",
    "ru": "Каждую минуту",
    "pt": "Cada minuto",
    "nl": "Elke minuut",
    "fr": "Chaque minute",
    "it": "Ogni minuto",
    "es": "Cada minuto",
    "pl": "Co minutę",
    "zh-cn": "每分钟"
  },
  "Every 2 minutes": {
    "en": "Every 2 minutes",
    "de": "Alle 2 Minuten",
    "ru": "Каждые 2 минуты",
    "pt": "A cada 2 minutos",
    "nl": "Om de twee minuten",
    "fr": "Toutes les 2 minutes",
    "it": "Ogni 2 minuti",
    "es": "Cada 2 minutos",
    "pl": "Co 2 minuty",
    "zh-cn": "每分钟2分钟"
  },
  "Every 3 minutes": {
    "en": "Every 3 minutes",
    "de": "Alle 3 Minuten",
    "ru": "Каждые 3 минуты",
    "pt": "A cada 3 minutos",
    "nl": "Om de drie minuten",
    "fr": "Toutes les 3 minutes",
    "it": "Ogni 3 minuti",
    "es": "Cada 3 minutos",
    "pl": "Co 3 minuty",
    "zh-cn": "每分钟3分钟"
  },
  "Every 4 minutes": {
    "en": "Every 4 minutes",
    "de": "Alle 4 Minuten",
    "ru": "Каждые 4 минуты",
    "pt": "A cada 4 minutos",
    "nl": "Om de vier minuten",
    "fr": "Toutes les 4 minutes",
    "it": "Ogni 4 minuti",
    "es": "Cada 4 minutos",
    "pl": "Co 4 minuty",
    "zh-cn": "每分钟4分钟"
  },
  "Every 5 minutes": {
    "en": "Every 5 minutes",
    "de": "Alle 5 Minuten",
    "ru": "Каждые 5 минут",
    "pt": "A cada 5 minutos",
    "nl": "Elke 5 minuten",
    "fr": "Toutes les 5 minutes",
    "it": "Ogni 5 minuti",
    "es": "Cada 5 minutos",
    "pl": "Co 5 minut",
    "zh-cn": "每5分钟"
  },
  "Every 10 minutes": {
    "en": "Every 10 minutes",
    "de": "Alle 10 Minuten",
    "ru": "Каждые 10 минут",
    "pt": "A cada 10 minutos",
    "nl": "Elke 10 minuten",
    "fr": "Toutes les 10 minutes",
    "it": "Ogni 10 minuti",
    "es": "Cada 10 minutos",
    "pl": "Co 10 minut",
    "zh-cn": "每10分钟"
  },
  "Every 15 minutes": {
    "en": "Every 15 minutes",
    "de": "Alle 15 Minuten",
    "ru": "Каждые 15 минут",
    "pt": "A cada 15 minutos",
    "nl": "Elke 15 minuten",
    "fr": "Toutes les 15 minutes",
    "it": "Ogni 15 minuti",
    "es": "Cada 15 minutos",
    "pl": "Co 15 minut",
    "zh-cn": "每15分钟"
  },
  "Every 20 minutes": {
    "en": "Every 20 minutes",
    "de": "Alle 20 Minuten",
    "ru": "Каждые 20 минут",
    "pt": "A cada 20 minutos",
    "nl": "Elke 20 minuten",
    "fr": "Toutes les 20 minutes",
    "it": "Ogni 20 minuti",
    "es": "Cada 20 minutos",
    "pl": "Co 20 minut",
    "zh-cn": "每20分钟"
  },
  "Every 25 minutes": {
    "en": "Every 25 minutes",
    "de": "Alle 25 Minuten",
    "ru": "Каждые 25 минут",
    "pt": "A cada 25 minutos",
    "nl": "Elke 25 minuten",
    "fr": "Toutes les 25 minutes",
    "it": "Ogni 25 minuti",
    "es": "Cada 25 minutos",
    "pl": "Co 25 minut",
    "zh-cn": "每25分钟"
  },
  "Every 30 minutes": {
    "en": "Every 30 minutes",
    "de": "Alle 30 Minuten",
    "ru": "Каждые 30 минут",
    "pt": "A cada 30 minutos",
    "nl": "Elke 30 minuten",
    "fr": "Toutes les 30 minutes",
    "it": "Ogni 30 minuti",
    "es": "Cada 30 minutos",
    "pl": "Co 30 minut",
    "zh-cn": "每30分钟"
  },
  "Every 15 minutes": {
    "en": "Every 15 minutes",
    "de": "Alle 15 Minuten",
    "ru": "Каждые 15 минут",
    "pt": "A cada 15 minutos",
    "nl": "Elke 15 minuten",
    "fr": "Toutes les 15 minutes",
    "it": "Ogni 15 minuti",
    "es": "Cada 15 minutos",
    "pl": "Co 15 minut",
    "zh-cn": "每15分钟"
  },
  "Every 35 minutes": {
    "en": "Every 35 minutes",
    "de": "Alle 35 Minuten",
    "ru": "Каждые 35 минут",
    "pt": "A cada 35 minutos",
    "nl": "Elke 35 minuten",
    "fr": "Toutes les 35 minutes",
    "it": "Ogni 35 minuti",
    "es": "Cada 35 minutos",
    "pl": "Co 35 minut",
    "zh-cn": "每35分钟"
  },
  "Every 35 minutes": {
    "en": "Every 35 minutes",
    "de": "Alle 35 Minuten",
    "ru": "Каждые 35 минут",
    "pt": "A cada 35 minutos",
    "nl": "Elke 35 minuten",
    "fr": "Toutes les 35 minutes",
    "it": "Ogni 35 minuti",
    "es": "Cada 35 minutos",
    "pl": "Co 35 minut",
    "zh-cn": "每35分钟"
  },
  "Every 40 minutes": {
    "en": "Every 40 minutes",
    "de": "Alle 40 Minuten",
    "ru": "Каждые 40 минут",
    "pt": "A cada 40 minutos",
    "nl": "Elke 40 minuten",
    "fr": "Toutes les 40 minutes",
    "it": "Ogni 40 minuti",
    "es": "Cada 40 minutos",
    "pl": "Co 40 minut",
    "zh-cn": "每40分钟"
  },
  "Every 45 minutes": {
    "en": "Every 45 minutes",
    "de": "Alle 45 Minuten",
    "ru": "Каждые 45 минут",
    "pt": "A cada 45 minutos",
    "nl": "Elke 45 minuten",
    "fr": "Toutes les 45 minutes",
    "it": "Ogni 45 minuti",
    "es": "Cada 45 minutos",
    "pl": "Co 45 minut",
    "zh-cn": "每45分钟"
  },
  "Every 50 minutes": {
    "en": "Every 50 minutes",
    "de": "Alle 50 Minuten",
    "ru": "Каждые 50 минут",
    "pt": "A cada 50 minutos",
    "nl": "Elke 50 minuten",
    "fr": "Toutes les 50 minutes",
    "it": "Ogni 50 minuti",
    "es": "Cada 50 minutos",
    "pl": "Co 50 minut",
    "zh-cn": "每50分钟"
  },
  "Every 55 minutes": {
    "en": "Every 55 minutes",
    "de": "Alle 55 Minuten",
    "ru": "Каждые 55 минут",
    "pt": "A cada 55 minutos",
    "nl": "Elke 55 minuten",
    "fr": "Toutes les 55 minutes",
    "it": "Ogni 55 minuti",
    "es": "Cada 55 minutos",
    "pl": "Co 55 minut",
    "zh-cn": "每55分钟"
  },
  "Every 60 minutes": {
    "en": "Every 60 minutes",
    "de": "Alle 60 Minuten",
    "ru": "Каждые 60 минут",
    "pt": "A cada 60 minutos",
    "nl": "Elke 60 minuten",
    "fr": "Toutes les 60 minutes",
    "it": "Ogni 60 minuti",
    "es": "Cada 60 minutos",
    "pl": "Co 60 minut",
    "zh-cn": "每60分钟"
  },
  "Warning: This interval is not recommended because errors are common at this interval.": {
    "en": "Warning: This interval is not recommended because errors are common at this interval.",
    "de": "Warnung: Dieses Intervall wird nicht empfohlen, da Fehler in diesem Intervall üblich sind.",
    "ru": "Предупреждение: Этот интервал не рекомендуется, потому что ошибки распространены в этом интервале.",
    "pt": "Atenção: Este intervalo não é recomendado porque os erros são comuns neste intervalo.",
    "nl": "Waarschuwing: Deze interval wordt niet aanbevolen omdat fouten normaal zijn in deze interval.",
    "fr": "Attention : Cet intervalle n'est pas recommandé car les erreurs sont courantes à cet intervalle.",
    "it": "Attenzione: Questo intervallo non è raccomandato perché gli errori sono comuni a questo intervallo.",
    "es": "Advertencia: Este intervalo no se recomienda porque los errores son comunes a este intervalo.",
    "pl": "Warning (ang.). Przedział ten nie jest zalecany, ponieważ błędy są powszechne w tej przerwie.",
    "zh-cn": "警告: 这种间隔不建议,因为这一间隔出现错误。."
  },
  "name": {
    "en": "name",
    "de": "Name",
    "ru": "название",
    "pt": "nome",
    "nl": "naam",
    "fr": "Nom",
    "it": "nome",
    "es": "nombre",
    "pl": "imię",
    "zh-cn": "名称"
  },
  "active": {
    "en": "active",
    "de": "Aktiv",
    "ru": "Активный",
    "pt": "Ativo",
    "nl": "Actief",
    "fr": "actif",
    "it": "Attivo",
    "es": "Activo",
    "pl": "Aktywny",
    "zh-cn": "活性"
  },
  "latitude": {
    "en": "latitude",
    "de": "Breitengrad",
    "ru": "широта",
    "pt": "latitude",
    "nl": "breedtegraad",
    "fr": "latitude",
    "it": "latitudine",
    "es": "latitud",
    "pl": "szerokość",
    "zh-cn": "纬度"
  },
  "longitude": {
    "en": "longitude",
    "de": "Längengrad",
    "ru": "долгота",
    "pt": "longitude",
    "nl": "Lengtegraad",
    "fr": "longitude",
    "it": "longitudine",
    "es": "longitud",
    "pl": "długość geograficzna",
    "zh-cn": "经度"
  },
  "Radius for location determination": {
    "en": "Radius for location determination",
    "de": "Radius für Standortbestimmung",
    "ru": "Радиус для определения местоположения",
    "pt": "Radius para determinação de localização",
    "nl": "Radius voor locatiebepaling",
    "fr": "Radius for location determination",
    "it": "Radius per la determinazione della posizione",
    "es": "Radius for location determination",
    "pl": "Radius dla określenia lokalizacji",
    "zh-cn": "确定地点的Radius"
  },
  "Note: In meters": {
    "en": "Note: In meters",
    "de": "Hinweis: Angabe in Metern",
    "ru": "Примечание: В метрах",
    "pt": "Nota: Em metros",
    "nl": "In Meters",
    "fr": "Note: En mètres",
    "it": "Nota: In metri",
    "es": "Nota: En metros",
    "pl": "Uwaga: w licznikach",
    "zh-cn": "注:"
  },
  "Locations": {
    "en": "Locations",
    "de": "Standorte",
    "ru": "Локации",
    "pt": "Localizações",
    "nl": "Locaties",
    "fr": "Emplacements",
    "it": "Posizioni",
    "es": "Ubicaciones",
    "pl": "Lokalizacje",
    "zh-cn": "地点"
  },
  "adaptersettings": {
    "en": "adaptersettings",
    "de": "Adaptereinstellungen",
    "ru": "настройки адаптера",
    "pt": "adaptersettings",
    "nl": "adapterinstellingen",
    "fr": "adaptateurs",
    "it": "adattatori",
    "es": "adaptadores",
    "pl": "ustawienia adapterów",
    "zh-cn": "适配器设置"
  },
  "Show devices from familygroup": {
    "en": "Show devices from familygroup",
    "de": "Geräte aus der Familiengruppe anzeigen",
    "ru": "Показать устройства из семейной группы",
    "pt": "Mostrar dispositivos do grupo familiar",
    "nl": "Toon apparaten van familiegroep",
    "fr": "Afficher les appareils du groupe familial",
    "it": "Mostra i dispositivi del gruppo famiglia",
    "es": "Mostrar dispositivos del grupo familiar",
    "pl": "Pokaż urządzenia z grupy rodzinnej",
    "zh-cn": "显示家庭组中的设备"
  },
  "Map-Provider": {
    "en": "Map-Provider",
    "de": "Kartenanbieter",
    "ru": "Картографический провайдер",
    "pt": "Provedor de mapas",
    "nl": "Kaartaanbieder",
    "fr": "Fournisseur de carte",
    "it": "Fornitore di mappe",
    "es": "Proveedor de mapas",
    "pl": "Dostawca mapy",
    "zh-cn": "地图提供者"
  },
  "API-Key": {
    "en": "API-Key",
    "de": "API-Schlüssel",
    "ru": "API-ключ",
    "pt": "Chave API",
    "nl": "API sleutel",
    "fr": "Clé API",
    "it": "Chiave API",
    "es": "Clave API",
    "pl": "Klucz API",
    "zh-cn": "API密钥"
  }
  

};